// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "William Luna"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/characters": {
            "get": {
                "description": "Retorna todos los personajes almacenados en Firestore",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Listar personajes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/domain.Character"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Crea un nuevo personaje con UUID autogenerado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Crear personaje",
                "parameters": [
                    {
                        "description": "Datos del personaje",
                        "name": "character",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Character"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/domain.Character"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/characters/devil-fruits": {
            "get": {
                "description": "Retorna solo los personajes que poseen una Fruta del Diablo",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Personajes con Fruta del Diablo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/domain.Character"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/characters/search": {
            "get": {
                "description": "Búsqueda por prefix en Firestore (case-sensitive). Ej: \"Monkey\" encuentra \"Monkey D. Luffy\"",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Buscar personajes por nombre",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Prefijo del nombre a buscar",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/domain.Character"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/characters/{id}": {
            "get": {
                "description": "Retorna un personaje específico dado su UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Obtener personaje por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID del personaje",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/domain.Character"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza un personaje existente por ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Actualizar personaje",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID del personaje",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos actualizados",
                        "name": "character",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Character"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/domain.Character"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina un personaje y todos sus datos normalizados",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Eliminar personaje",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID del personaje",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/islands": {
            "get": {
                "description": "Retorna las 30 islas canónicas del mundo de One Piece con coordenadas 2D",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "islands"
                ],
                "summary": "Listar todas las islas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Island"
                            }
                        }
                    }
                }
            }
        },
        "/api/islands/nearest": {
            "get": {
                "description": "Dado un punto (x,y) del mapa, retorna la isla más cercana usando un índice Quadtree 2D. Coordenadas: X 0-10000 (Oeste→Este), Y 0-5000 (Sur→Norte). La Grand Line corre en Y≈2500.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "islands"
                ],
                "summary": "Isla más cercana (Quadtree)",
                "parameters": [
                    {
                        "type": "number",
                        "example": 4300,
                        "description": "Coordenada X del mapa (0-10000)",
                        "name": "x",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "example": 2500,
                        "description": "Coordenada Y del mapa (0-5000)",
                        "name": "y",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Island"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/islands/region/{region}": {
            "get": {
                "description": "Filtra islas por región (East Blue, Grand Line, New World, Sky Islands, Red Line)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "islands"
                ],
                "summary": "Islas por región",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nombre de la región",
                        "name": "region",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Island"
                            }
                        }
                    }
                }
            }
        },
        "/api/islands/{id}": {
            "get": {
                "description": "Retorna el detalle de una isla dado su slug (ej: water-7, laugh-tale)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "islands"
                ],
                "summary": "Obtener isla por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug de la isla (ej: water-7)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Island"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/proxy/image": {
            "get": {
                "description": "Descarga una imagen desde una URL externa y la sirve al cliente, evitando CORS y hotlink protection",
                "produces": [
                    "image/png"
                ],
                "tags": [
                    "proxy"
                ],
                "summary": "Proxy de imagen externa",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL de la imagen a proxear",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/routes": {
            "get": {
                "description": "Retorna todas las rutas marítimas registradas en Firestore",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routes"
                ],
                "summary": "Listar rutas marítimas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Route"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/routes/from/{islandID}": {
            "get": {
                "description": "Retorna todas las rutas en las que la isla indicada participa como origen o destino",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routes"
                ],
                "summary": "Rutas desde/hacia una isla",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la isla",
                        "name": "islandID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Route"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/routes/reachable": {
            "get": {
                "description": "Retorna todas las islas alcanzables desde el origen cuyo costo (suma de distancias) sea menor o igual a maxCost. Usa Dijkstra (modo fastest).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routes"
                ],
                "summary": "Islas alcanzables",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la isla origen",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Costo máximo permitido",
                        "name": "maxCost",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ReachableResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/routes/shortest": {
            "get": {
                "description": "Calcula la ruta óptima entre dos islas según el modo elegido.\n- **fastest** (default): minimiza la suma de distancias.\n- **quickest**: minimiza el tiempo total (TravelHours de rutas + LogPoseHours de islas intermedias).\n- **safest**: minimiza el peligro del peor tramo (minimax sobre Danger).\n- **riskiest**: maximiza el peligro del mejor tramo (maximin sobre Danger).\nLa respuesta SIEMPRE incluye las 4 métricas globales (` + "`" + `totalDistance` + "`" + `, ` + "`" + `totalTime` + "`" + `, ` + "`" + `worstDanger` + "`" + `, ` + "`" + `bestDanger` + "`" + `) calculadas sobre el camino encontrado, independientemente del modo.\nEl campo legacy ` + "`" + `totalCost` + "`" + ` refleja la métrica del modo activo (clientes nuevos deberían usar las 4 explícitas).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routes"
                ],
                "summary": "Ruta más corta (Dijkstra)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la isla origen",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID de la isla destino",
                        "name": "to",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "fastest",
                            "quickest",
                            "safest",
                            "riskiest"
                        ],
                        "type": "string",
                        "default": "fastest",
                        "description": "Modo de búsqueda",
                        "name": "mode",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ShortestPathResponse"
                        }
                    },
                    "400": {
                        "description": "Parámetros faltantes o modo inválido",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No existe ruta navegable",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/routes/stats": {
            "get": {
                "description": "Retorna metricas estructurales del grafo: totales, promedios (distancia, tiempo, danger), distribucion de Danger por nivel (1-5) y numero de componentes conectados.\nUtil para visualizar la salud del seed y construir vistas de analisis.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routes"
                ],
                "summary": "Estadisticas del grafo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GraphStats"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "controller.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "domain.Ability": {
            "type": "object",
            "properties": {
                "notes": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.Character": {
            "type": "object",
            "properties": {
                "abilities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Ability"
                    }
                },
                "alias": {
                    "type": "string"
                },
                "devilFruit": {
                    "$ref": "#/definitions/domain.DevilFruit"
                },
                "firstAppearance": {
                    "type": "string"
                },
                "hakiAbilities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.HakiAbility"
                    }
                },
                "id": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "species": {
                    "type": "string"
                }
            }
        },
        "domain.DevilFruit": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.GraphStats": {
            "type": "object",
            "properties": {
                "avgDanger": {
                    "type": "number"
                },
                "avgDistance": {
                    "type": "number"
                },
                "avgTravelHours": {
                    "type": "number"
                },
                "bidirectionalCount": {
                    "type": "integer"
                },
                "connectedComponents": {
                    "type": "integer"
                },
                "dangerHistogram": {
                    "description": "DangerHistogram[i] = cantidad de rutas con Danger == i+1 (i en [0..4]).",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "islandsWithLogPose": {
                    "type": "integer"
                },
                "largestComponent": {
                    "type": "integer"
                },
                "totalIslands": {
                    "type": "integer"
                },
                "totalRoutes": {
                    "type": "integer"
                }
            }
        },
        "domain.HakiAbility": {
            "type": "object",
            "properties": {
                "awakened": {
                    "type": "boolean"
                },
                "hakiType": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "proficiency": {
                    "type": "string"
                }
            }
        },
        "domain.Island": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "logPoseHours": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "notableCharacters": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "region": {
                    "type": "string"
                },
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                }
            }
        },
        "domain.PathStep": {
            "type": "object",
            "properties": {
                "bestDangerSoFar": {
                    "type": "integer"
                },
                "costSoFar": {
                    "type": "number"
                },
                "distanceSoFar": {
                    "type": "number"
                },
                "islandId": {
                    "type": "string"
                },
                "islandName": {
                    "type": "string"
                },
                "timeSoFar": {
                    "type": "number"
                },
                "worstDangerSoFar": {
                    "type": "integer"
                }
            }
        },
        "domain.ReachableIsland": {
            "type": "object",
            "properties": {
                "cost": {
                    "type": "number"
                },
                "islandId": {
                    "type": "string"
                },
                "islandName": {
                    "type": "string"
                }
            }
        },
        "domain.ReachableResponse": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "islands": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ReachableIsland"
                    }
                },
                "maxCost": {
                    "type": "number"
                }
            }
        },
        "domain.Route": {
            "type": "object",
            "properties": {
                "bidirectional": {
                    "type": "boolean"
                },
                "danger": {
                    "description": "1-5",
                    "type": "integer"
                },
                "distance": {
                    "type": "number"
                },
                "fromIsland": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "toIsland": {
                    "type": "string"
                },
                "travelHours": {
                    "type": "number"
                },
                "weight": {
                    "description": "Deprecated: Weight es un peso precalculado heredado del primer Dijkstra\n(Distance * DangerMultiplier(Danger)). Los modos de busqueda actuales\n(fastest/safest/riskiest/quickest) calculan el peso dinamicamente desde\nDistance, TravelHours o Danger segun el modo. Se conserva para no migrar\nFirestore; no usar en codigo nuevo.",
                    "type": "number"
                }
            }
        },
        "domain.RouteMode": {
            "type": "string",
            "enum": [
                "fastest",
                "quickest",
                "safest",
                "riskiest"
            ],
            "x-enum-varnames": [
                "RouteModeFastest",
                "RouteModeQuickest",
                "RouteModeSafest",
                "RouteModeRiskiest"
            ]
        },
        "domain.ShortestPathResponse": {
            "type": "object",
            "properties": {
                "bestDanger": {
                    "type": "integer"
                },
                "found": {
                    "type": "boolean"
                },
                "from": {
                    "type": "string"
                },
                "hops": {
                    "type": "integer"
                },
                "mode": {
                    "$ref": "#/definitions/domain.RouteMode"
                },
                "path": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.PathStep"
                    }
                },
                "to": {
                    "type": "string"
                },
                "totalCost": {
                    "description": "TotalCost (legacy) refleja la metrica del modo activo.",
                    "type": "number"
                },
                "totalDistance": {
                    "description": "Metricas globales del camino encontrado. Siempre presentes.",
                    "type": "number"
                },
                "totalTime": {
                    "type": "number"
                },
                "worstDanger": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Requerido para POST, PUT y DELETE. Configura la variable de entorno API_KEY en el servidor.",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "One Piece API",
	Description:      "API REST para gestionar personajes e islas del mundo de One Piece. Proyecto de estudio con Clean Architecture en Go + Firestore.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
